<?php

use Drupal\Core\Render\Markup;
use Drupal\node\NodeInterface;
use Drupal\product_catalog\ImageSearch;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function product_catalog_views_pre_render(ViewExecutable $view) {
  if (($view->storage->id() == 'product_catalog')) {
    $view->element['#attached']['library'][] = 'product_catalog/product-catalog';
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function product_catalog_node_presave(\Drupal\Core\Entity\EntityInterface $node) {

  // Search for an image on node creating
  if($node->bundle() === 'products' && $node->isNew()) {
    $keywords = $node->getTitle();
    $image_search = new ImageSearch();
    $url = $image_search->get_image($keywords);

    $node->set('field_image_url', $url);
  }
}
