product_catalog.product_import:
  title: 'Product Import'
  description: 'Import Products through CSV files.'
  route_name: product_catalog.import
  parent: system.admin_config_content
product_catalog.image_search.settings:
  title: 'Image Search Settings'
  description: 'Configure the Image Search Setting for the Product Catalog module.'
  route_name: product_catalog.image_search.settings
  parent: system.admin_config_search
