product-catalog:
  css:
    theme:
      css/product-catalog.css: {}
  js:
    js/product-catalog.js: {}
  dependencies:
    - core/jquery
    - core/once
    - core/drupal
    - product_catalog/fontawesome

fontawesome:
  remote: https://fontawesome.com/
  license:
    name: CC BY 4.0
    url: https://fontawesome.com/license
    gpl-compatible: true
  version: "6.3.0"
  header: true
  css:
    component:
      //cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css: { minified: true, external: true }

